# Generated by Django 3.2.6 on 2021-09-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(default='', max_length=250)),
                ('NumeroUC', models.CharField(default='', max_length=250)),
                ('UCsCompensacao', models.JSONField(default={})),
                ('Localizacao', models.CharField(default='', max_length=380)),
                ('CEP', models.CharField(default='', max_length=40)),
                ('Bairro', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(default='', max_length=200)),
                ('Telefone', models.CharField(default='', max_length=250)),
                ('CPF_CNPJ', models.CharField(default='', max_length=250)),
                ('ValorEFormaPagamento', models.TextField(default='', max_length=2500)),
                ('Notas', models.TextField(default='', max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaTecnica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RespostaTecnica', models.JSONField(default={})),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaComercial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RespostaComercial', models.JSONField(default={})),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='DadosConcessionarias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CargaInstalada', models.FloatField()),
                ('PadraoEntrada', models.TextField(default='', max_length=2500)),
                ('TensaoAtendimento', models.TextField(default='', max_length=2500)),
                ('TipoConexao', models.TextField(default='', max_length=2500)),
                ('PotenciaInstalada', models.FloatField()),
                ('PotenciaModulos', models.FloatField()),
                ('PotenciaInversores', models.FloatField()),
                ('NumeroArranjos', models.IntegerField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
    ]
